### ISSUE TITLE
can't dowload NTU hand digit dataset

### ISSUE THREAD

**Issue by waterai12** [Ha0Tang/GestureGAN#3]
The download link in the paper is broken. Do you know where else to download?

**Comment by Ha0Tang** [comment]
The download link provided in this repro should be fine. Can you try again?

**Comment by waterai12** [comment]
> The download link provided in this repro should be fine. Can you try again?

Is this link (http://www.ntu.edu.sg/home/renzhou/HandGesture.htm) ?    I tried but faild

**Comment by Ha0Tang** [comment]
We also noticed that the original download link has expired, so we provided the prepared data [here](https://github.com/Ha0Tang/GestureGAN#dataset-preparation).

**Comment by waterai12** [comment]
> We also noticed that the original download link has expired, so we provided the prepared data [here](https://github.com/Ha0Tang/GestureGAN#dataset-preparation).

Thank you for answering my question, I found it.
