### ISSUE TITLE
Filter failure cases manually from train set?

### ISSUE THREAD

**Issue by jysa01** [Ha0Tang/GestureGAN#6]
I am interested to understand the working of gestureGAN_twocycle model. I downloaded the senz3d dataset and prepared training and test data as indicated. When I saw the training output, I noticed that there are many images for which the pose is wrongly identified. Did you manually delete them from the 135,504 training samples? Can you please provide a .txt file with the correct sample's filenames ? 
Thanks and best regards,
jysa01

**Comment by Ha0Tang** [comment]
Can you share with me some examples?

**Comment by jysa01** [comment]
Below are some samples from the train set : 
**G5_S3_7-color_G6_S3_1-color_AB_lr.png**
![image](https://user-images.githubusercontent.com/40629869/117581385-bd5a7000-b0fc-11eb-8d0d-a7ab61e1c652.png)
**G5_S3_5-color_G1_S3_13-color.png**
![image](https://user-images.githubusercontent.com/40629869/117581649-4cb45300-b0fe-11eb-819c-080a4eebdf25.png)
**G3_S4_20-color_G6_S4_1-color_AB_lr.png**
![image](https://user-images.githubusercontent.com/40629869/117581760-c8ae9b00-b0fe-11eb-8cd1-f3ccfa744e3f.png)

**Comment by Ha0Tang** [comment]
If you prepared the data according to the instructions I provided, there should be nothing wrong. I used all 135,504 samples for training.

**Comment by jysa01** [comment]
OK, Thank you :) 
Yes, I did follow all the steps. 
From my understanding, the Matlab code provided prepares each data sample as [A,B,C,D] by reading each filename given in `senz3d_split/senz3d_train.txt` from the folders `senz3d_image_skeleton/senz3d_skeleton` and `senz3d_image_skeleton/senz3d_image` respectively. 

So, the skeleton inside the senz3d_skeleton folder for the sample **G5_S3_5-color_G1_S3_13-color.png** is: 
**G5_S3_5-color.png**
![G5_S3_5-color](https://user-images.githubusercontent.com/40629869/117631549-a3607200-b17c-11eb-9780-31014cf49782.png)

I seem to have interpreted this as a wrong pose. Thank you for the clarification.
