### ISSUE TITLE
Is there any way I can use the pretrained model to fine-tune it?

### ISSUE THREAD

**Issue by ali-ahnaf** [Ha0Tang/GestureGAN#8]
I'm trying to use the pre-trained model in my training process with my own dataset. It keeps throwing the error: `No file found latest_net_D1.pth`. I only used the flag `--continue-training`.

**Comment by Ha0Tang** [comment]
For fine-tuning, the discriminator model (latest_net_D1.pth) is required, but we can't provide it because I can't find it anymore. I suggest you train from scratch yourself and then fine-tune on your data.
